### ISSUE TITLE
Switching off InspectorFloret in viewController does not disable it

### ISSUE THREAD

**Issue by Shukuyen** [cauliframework/cauli#122]
Repro:
- Instantiate Cauli with inspector floret
- Disable inspector floret before calling run()
- Create some network requests
- Open cauli.viewcontroller

Expected:
- Inspector floret is disabled and list of requests is empty

Actual:
- Inspector floret is disabled but the recent requests show in the list

**Comment by pstued** [comment]
Since almost a month passed I'll just summarise what's still needs to be done for version 1.0. If I got anything wrong, please let me now @brototyp @Shukuyen 

1. Add more documentation describing the affects of enabling and disabling a floret (I'll go with the table footer)
2. Add switch to enable/disable the cauli instance itself

**Comment by brototyp** [comment]
So what I had in mind was to

* split up the Floret protocols, so for the InspectorFloret there will be no switch to to disable it
* add a note to the footer explaining what the sections actually are and what disabling a section means

I am not opposed to adding a general enable/disable cauli switch, but I don't think it would change anything in regards to this issue here. If we want to add such a switch, we should talk about where to add it.

**Comment by pstued** [comment]
I splitter that ticket into three single tickets.
